when not defined(cpp):
  {.error: "C++ backend required to use minidocx".}

import std/os
import cppstl

const
  currentDir = currentSourcePath.parentDir()
  minidocxHeaderPath {.strdefine.} = currentDir / "../minidocx-lib/src/minidocx.hpp"
  minidocxSourcePath {.strdefine.} = currentDir / "../minidocx-lib/src/minidocx.cpp"
  zipDirectory {.strdefine.} = currentDir / "../minidocx-lib/3rdparty/zip-0.2.1"
  zipSourcePath {.strdefine.} = currentDir / "../minidocx-lib/3rdparty/zip-0.2.1/zip.c"
  pugixmlDirectory {.strdefine.} = currentDir / "../minidocx-lib/3rdparty/pugixml-1.13"
  pugixmlSourcePath {.strdefine.} = currentDir / "../minidocx-lib/3rdparty/pugixml-1.13/pugixml.cpp"

{.passc: "-I" & zipDirectory & " -I" & pugixmlDirectory.}
{.compile: zipSourcePath.}
{.compile: pugixmlSourcePath.}
{.compile: minidocxSourcePath.}

converter toStr*(s: string): CppString =
  initCppString(s)

type
  CppMap*[K, V] {.importcpp: "std::map", header: "<map>".} = object

proc `[]=`*[K, V](this: var CppMap[K, V]; key: K; val: V) {.
  importcpp: "#[#] = #", header: "<map>".}

proc mixFlags*[T: enum](flags: varargs[T]): T =
  ## Mixes flags as in C++: `Flag | Flag`.
  var res = 0
  for x in flags:
    res = res or int(x)

  result = T res

{.push header: minidocxHeaderPath.}

# Generated by c2nim, using the following command: c2nim --cpp --header --importc --strict --debug src/minidocx-lib/src/minidocx.hpp
# Tweaked by hand a bit

let PPI* {.importcpp.}: cint

##  inches

let A0_W* {.importcpp.}: cdouble

let A0_H* {.importcpp.}: cdouble

let A1_W* {.importcpp.}: cdouble

let A1_H* {.importcpp.}: cdouble

let A2_W* {.importcpp.}: cdouble

let A2_H* {.importcpp.}: cdouble

let A3_W* {.importcpp.}: cdouble

let A3_H* {.importcpp.}: cdouble

let A4_W* {.importcpp.}: cdouble

let A4_H* {.importcpp.}: cdouble

let A5_W* {.importcpp.}: cdouble

let A5_H* {.importcpp.}: cdouble

let A6_W* {.importcpp.}: cdouble

let A6_H* {.importcpp.}: cdouble

let LETTER_W* {.importcpp.}: cdouble

let LETTER_H* {.importcpp.}: cdouble

let LEGAL_W* {.importcpp.}: cdouble

let LEGAL_H* {.importcpp.}: cdouble

let TABLOID_W* {.importcpp.}: cdouble

let TABLOID_H* {.importcpp.}: cdouble

##  pixels

let A0_COLS* {.importcpp.}: cuint

let A0_ROWS* {.importcpp.}: cuint

let A1_COLS* {.importcpp.}: cuint

let A1_ROWS* {.importcpp.}: cuint

let A2_COLS* {.importcpp.}: cuint

let A2_ROWS* {.importcpp.}: cuint

let A3_COLS* {.importcpp.}: cuint

let A3_ROWS* {.importcpp.}: cuint

let A4_COLS* {.importcpp.}: cuint

let A4_ROWS* {.importcpp.}: cuint

let A5_COLS* {.importcpp.}: cuint

let A5_ROWS* {.importcpp.}: cuint

let A6_COLS* {.importcpp.}: cuint

let A6_ROWS* {.importcpp.}: cuint

let LETTER_COLS* {.importcpp.}: cuint

let LETTER_ROWS* {.importcpp.}: cuint

let LEGAL_COLS* {.importcpp.}: cuint

let LEGAL_ROWS* {.importcpp.}: cuint

let TABLOID_COLS* {.importcpp.}: cuint

let TABLOID_ROWS* {.importcpp.}: cuint

proc pt2Twip*(pt: cdouble): cint {.importcpp: "Pt2Twip",
                               importcpp: "docx::Pt2Twip(@)".}
proc twip2Pt*(twip: cint): cdouble {.importcpp: "Twip2Pt",
                                 importcpp: "docx::Twip2Pt(@)".}
proc inch2Pt*(inch: cdouble): cdouble {.importcpp: "Inch2Pt",
                                    importcpp: "docx::Inch2Pt(@)".}
proc pt2Inch*(pt: cdouble): cdouble {.importcpp: "Pt2Inch",
                                  importcpp: "docx::Pt2Inch(@)".}
proc mM2Inch*(mm: cint): cdouble {.importcpp: "MM2Inch",
                               importcpp: "docx::MM2Inch(@)".}
proc inch2MM*(inch: cdouble): cint {.importcpp: "Inch2MM",
                                 importcpp: "docx::Inch2MM(@)".}
proc cM2Inch*(cm: cdouble): cdouble {.importcpp: "CM2Inch",
                                  importcpp: "docx::CM2Inch(@)".}
proc inch2CM*(inch: cdouble): cdouble {.importcpp: "Inch2CM",
                                    importcpp: "docx::Inch2CM(@)".}
proc inch2Twip*(inch: cdouble): cint {.importcpp: "Inch2Twip",
                                   importcpp: "docx::Inch2Twip(@)".}
proc twip2Inch*(twip: cint): cdouble {.importcpp: "Twip2Inch",
                                   importcpp: "docx::Twip2Inch(@)".}
proc mM2Twip*(mm: cint): cint {.importcpp: "MM2Twip", importcpp: "docx::MM2Twip(@)".}
proc twip2MM*(twip: cint): cint {.importcpp: "Twip2MM", importcpp: "docx::Twip2MM(@)".}
proc cM2Twip*(cm: cdouble): cint {.importcpp: "CM2Twip",
                               importcpp: "docx::CM2Twip(@)".}
proc twip2CM*(twip: cint): cdouble {.importcpp: "Twip2CM",
                                 importcpp: "docx::Twip2CM(@)".}
discard "forward decl of Document"
discard "forward decl of Paragraph"
discard "forward decl of Section"
discard "forward decl of Run"
discard "forward decl of Table"
discard "forward decl of TableCell"
discard "forward decl of TextFrame"
type
  Box* {.importcpp: "docx::Box", bycopy.} = object

  BoxBorderStyle* {.size: sizeof(cint), importcpp: "docx::Box::BorderStyle".} = enum
    Single, Dotted, Dashed, DotDash, Double, Wave, None

  Cell* {.importcpp: "docx::Cell", bycopy.} = object
    row* {.importc: "row".}: cint
    col* {.importc: "col".}: cint ##  position
    rows* {.importc: "rows".}: cint
    cols* {.importc: "cols".}: cint ##  size

  Row* = CppVector[Cell]
  Grid* = CppVector[Row]

  TableCell* {.importcpp: "docx::TableCell", bycopy.} = object ##  constructs an empty cell
    ##  constructs a table from existing xml node

  TableCellAlignment* {.size: sizeof(cint),
                       importcpp: "docx::TableCell::Alignment".} = enum
    Top, Center, Bottom

  Table* {.importcpp: "docx::Table", bycopy.} = object #of Box ##  constructs an empty table
    ##  constructs a table from existing xml node

  TableAlignment* {.size: sizeof(cint), importcpp: "docx::Table::Alignment".} = enum
    Left, Centered, Right

  Run* {.importcpp: "docx::Run", bycopy.} = object ##  constructs an empty run
    ##  constructs run from existing xml node

  RunFontStyle* {.size: sizeof(cuint), importcpp: "docx::Run::FontStyle".} = enum
    Bold = 1, Italic = 2, Underline = 4, Strikethrough = 8

  Section* {.importcpp: "docx::Section", bycopy.} = object ##  constructs an empty section
    ##  constructs section from existing xml node

  SectionOrientation* {.size: sizeof(cint),
                       importcpp: "docx::Section::Orientation".} = enum
    Landscape, Portrait, Unknown

  SectionPageNumberFormat* {.size: sizeof(cint),
                            importcpp: "docx::Section::PageNumberFormat".} = enum
    Decimal,                  ##  e.g., 1, 2, 3, 4, etc.
    NumberInDash,             ##  e.g., -1-, -2-, -3-, -4-, etc.
    CardinalText,             ##  In English, One, Two, Three, etc.
    OrdinalText,              ##  In English, First, Second, Third, etc.
    LowerLetter,              ##  e.g., a, b, c, etc.
    UpperLetter,              ##  e.g., A, B, C, etc.
    LowerRoman,               ##  e.g., i, ii, iii, iv, etc.
    UpperRoman                ##  e.g., I, II, III, IV, etc.

  Paragraph* {.importcpp: "docx::Paragraph", bycopy.} = object #of Box ##  constructs an empty paragraph
    ##  constructs paragraph from existing xml node

  ParagraphAlignment* {.size: sizeof(cint),
                       importcpp: "docx::Paragraph::Alignment".} = enum
    Left, Centered, Right, Justified, Distributed

  TextFrame* {.importcpp: "docx::TextFrame", bycopy.} = object #of Paragraph ##  constructs an empty text frame
    ##  constructs text frame from existing xml node
  TextFrameAnchor* {.size: sizeof(cint), importcpp: "docx::TextFrame::Anchor".} = enum
    Page, Margin

  TextFramePosition* {.size: sizeof(cint), importcpp: "docx::TextFrame::Position".} = enum
    Left, Center, Right, Top, Bottom

  TextFrameWrapping* {.size: sizeof(cint), importcpp: "docx::TextFrame::Wrapping".} = enum
    Around, None

  Bookmark* {.importcpp: "docx::Bookmark", bycopy.} = object
  Document* {.importcpp: "docx::Document", bycopy.} = object ##  constructs an empty document

proc constructTableCell*(): TableCell {.constructor,
                                     importcpp: "docx::TableCell(@)".}
proc constructTableCell*(tc: TableCell): TableCell {.constructor,
    importcpp: "docx::TableCell(@)".}
proc destroyTableCell*(this: var TableCell) {.importcpp: "#.~TableCell()".}
converter toBool*(this: var TableCell): bool {.importcpp: "TableCell::operator bool".}
proc empty*(this: TableCell): bool {.noSideEffect, importcpp: "empty".}
proc setWidth*(this: var TableCell; w: cint; units: cstring = "dxa") {.
    importcpp: "SetWidth".}

proc setVerticalAlignment*(this: var TableCell; align: TableCellAlignment) {.
    importcpp: "SetVerticalAlignment".}
# proc setCellSpanning_*(this: var TableCell; cols: cint) {.
    # importcpp: "SetCellSpanning_".}
proc appendParagraph*(this: var TableCell): Paragraph {.importcpp: "AppendParagraph".}
proc firstParagraph*(this: var TableCell): Paragraph {.importcpp: "FirstParagraph".}
##  class TableCell

proc constructTable*(): Table {.constructor, importcpp: "docx::Table(@)".}
proc constructTable*(t: Table): Table {.constructor, importcpp: "docx::Table(@)".}
proc destroyTable*(this: var Table) {.importcpp: "#.~Table()".}
# proc create_*(this: var Table; rows: cint; cols: cint) {.importcpp: "Create_".}
# proc getCell*(this: var Table; row: cint; col: cint): TableCell {.importcpp: "GetCell".}
# proc getCell_*(this: var Table; row: cint; col: cint): TableCell {.importcpp: "GetCell_".}
proc mergeCells*(this: var Table; tc1: TableCell; tc2: TableCell): bool {.
    importcpp: "MergeCells".}
proc splitCell*(this: var Table): bool {.importcpp: "SplitCell".}
# proc removeCell_*(this: var Table; tc: TableCell) {.importcpp: "RemoveCell_".}
proc setWidthAuto*(this: var Table) {.importcpp: "SetWidthAuto".}
proc setWidthPercent*(this: var Table; w: cdouble) {.importcpp: "SetWidthPercent".}
proc setWidth*(this: var Table; w: cint; units: cstring = "dxa") {.importcpp: "SetWidth".}
proc setCellMarginTop*(this: var Table; w: cint; units: cstring = "dxa") {.
    importcpp: "SetCellMarginTop".}
proc setCellMarginBottom*(this: var Table; w: cint; units: cstring = "dxa") {.
    importcpp: "SetCellMarginBottom".}
proc setCellMarginLeft*(this: var Table; w: cint; units: cstring = "dxa") {.
    importcpp: "SetCellMarginLeft".}
proc setCellMarginRight*(this: var Table; w: cint; units: cstring = "dxa") {.
    importcpp: "SetCellMarginRight".}
proc setCellMargin*(this: var Table; elemName: cstring; w: cint; units: cstring = "dxa") {.
    importcpp: "SetCellMargin".}

proc setAlignment*(this: var Table; alignment: TableAlignment) {.
    importcpp: "SetAlignment".}
proc setTopBorders*(this: var Table; style: BoxBorderStyle = Single; width: cdouble = 0.5;
                   color: cstring = "auto") {.importcpp: "SetTopBorders".}
proc setBottomBorders*(this: var Table; style: BoxBorderStyle = Single;
                      width: cdouble = 0.5; color: cstring = "auto") {.
    importcpp: "SetBottomBorders".}
proc setLeftBorders*(this: var Table; style: BoxBorderStyle = Single; width: cdouble = 0.5;
                    color: cstring = "auto") {.importcpp: "SetLeftBorders".}
proc setRightBorders*(this: var Table; style: BoxBorderStyle = Single;
                     width: cdouble = 0.5; color: cstring = "auto") {.
    importcpp: "SetRightBorders".}
proc setInsideHBorders*(this: var Table; style: BoxBorderStyle = Single;
                       width: cdouble = 0.5; color: cstring = "auto") {.
    importcpp: "SetInsideHBorders".}
proc setInsideVBorders*(this: var Table; style: BoxBorderStyle = Single;
                       width: cdouble = 0.5; color: cstring = "auto") {.
    importcpp: "SetInsideVBorders".}
proc setInsideBorders*(this: var Table; style: BoxBorderStyle = Single;
                      width: cdouble = 0.5; color: cstring = "auto") {.
    importcpp: "SetInsideBorders".}
proc setOutsideBorders*(this: var Table; style: BoxBorderStyle = Single;
                       width: cdouble = 0.5; color: cstring = "auto") {.
    importcpp: "SetOutsideBorders".}
proc setAllBorders*(this: var Table; style: BoxBorderStyle = Single; width: cdouble = 0.5;
                   color: cstring = "auto") {.importcpp: "SetAllBorders".}
# proc setBorders_*(this: var Table; elemName: cstring; style: BoxBorderStyle;
                 # width: cdouble; color: cstring) {.importcpp: "SetBorders_".}
##  class Table

proc constructRun*(): Run {.constructor, importcpp: "docx::Run(@)".}
proc constructRun*(r: Run): Run {.constructor, importcpp: "docx::Run(@)".}
proc destroyRun*(this: var Run) {.importcpp: "#.~Run()".}
converter toBool*(this: var Run): bool {.importcpp: "Run::operator bool".}
proc next*(this: var Run): Run {.importcpp: "Next".}
proc appendText*(this: var Run; text: CppString) {.importcpp: "AppendText".}
proc getText*(this: var Run): CppString {.importcpp: "GetText".}
proc clearText*(this: var Run) {.importcpp: "ClearText".}
proc appendLineBreak*(this: var Run) {.importcpp: "AppendLineBreak".}
proc appendTabs*(this: var Run; count: cuint = 1) {.importcpp: "AppendTabs".}

proc setFontSize*(this: var Run; fontSize: cdouble) {.importcpp: "SetFontSize".}
proc getFontSize*(this: var Run): cdouble {.importcpp: "GetFontSize".}
proc setFont*(this: var Run; fontAscii: CppString; fontEastAsia: CppString = "") {.
    importcpp: "SetFont".}
proc getFont*(this: var Run; fontAscii: var string; fontEastAsia: var string) {.
    importcpp: "GetFont".}
proc setFontStyle*(this: var Run; fontStyle: RunFontStyle) {.
    importcpp: "SetFontStyle".}
proc getFontStyle*(this: var Run): RunFontStyle {.importcpp: "GetFontStyle".}
proc setCharacterSpacing*(this: var Run; characterSpacing: cint) {.
    importcpp: "SetCharacterSpacing".}
proc getCharacterSpacing*(this: var Run): cint {.importcpp: "GetCharacterSpacing".}
proc remove*(this: var Run) {.importcpp: "Remove".}
proc isPageBreak*(this: var Run): bool {.importcpp: "IsPageBreak".}
##  class Run

proc constructSection*(): Section {.constructor, importcpp: "docx::Section(@)".}
proc constructSection*(s: Section): Section {.constructor,
    importcpp: "docx::Section(@)".}
proc destroySection*(this: var Section) {.importcpp: "#.~Section()".}
proc `==`*(this: var Section; s: Section): bool {.importcpp: "(# == #)".}
converter toBool*(this: var Section): bool {.importcpp: "Section::operator bool".}
proc next*(this: var Section): Section {.importcpp: "Next".}
proc prev*(this: var Section): Section {.importcpp: "Prev".}
proc split*(this: var Section) {.importcpp: "Split".}
proc isSplit*(this: var Section): bool {.importcpp: "IsSplit".}
proc merge*(this: var Section) {.importcpp: "Merge".}

proc setPageSize*(this: var Section; w: cint; h: cint) {.importcpp: "SetPageSize".}
proc getPageSize*(this: var Section; w: var cint; h: var cint) {.importcpp: "GetPageSize".}
proc setPageOrient*(this: var Section; orient: SectionOrientation) {.
    importcpp: "SetPageOrient".}
proc getPageOrient*(this: var Section): SectionOrientation {.
    importcpp: "GetPageOrient".}
proc setPageMargin*(this: var Section; top: cint; bottom: cint; left: cint; right: cint) {.
    importcpp: "SetPageMargin".}
proc getPageMargin*(this: var Section; top: var cint; bottom: var cint; left: var cint;
                   right: var cint) {.importcpp: "GetPageMargin".}
proc setPageMargin*(this: var Section; header: cint; footer: cint) {.
    importcpp: "SetPageMargin".}
proc getPageMargin*(this: var Section; header: var cint; footer: var cint) {.
    importcpp: "GetPageMargin".}
proc setColumn*(this: var Section; num: cint; space: cint = 425) {.importcpp: "SetColumn".}

proc setPageNumber*(this: var Section; fmt: SectionPageNumberFormat = Decimal;
                   start: cuint = 0) {.importcpp: "SetPageNumber".}
proc removePageNumber*(this: var Section) {.importcpp: "RemovePageNumber".}
proc firstParagraph*(this: var Section): Paragraph {.importcpp: "FirstParagraph".}
proc lastParagraph*(this: var Section): Paragraph {.importcpp: "LastParagraph".}
##  class Section


proc constructParagraph*(): Paragraph {.constructor,
                                     importcpp: "docx::Paragraph(@)".}
proc constructParagraph*(p: Paragraph): Paragraph {.constructor,
    importcpp: "docx::Paragraph(@)".}
proc destroyParagraph*(this: var Paragraph) {.importcpp: "#.~Paragraph()".}
proc `==`*(this: var Paragraph; p: Paragraph): bool {.importcpp: "(# == #)".}
converter toBool*(this: var Paragraph): bool {.importcpp: "Paragraph::operator bool".}
proc next*(this: var Paragraph): Paragraph {.importcpp: "Next".}
proc prev*(this: var Paragraph): Paragraph {.importcpp: "Prev".}
proc firstRun*(this: var Paragraph): Run {.importcpp: "FirstRun".}
proc appendRun*(this: var Paragraph): Run {.importcpp: "AppendRun".}
proc appendRun*(this: var Paragraph; text: CppString): Run {.importcpp: "AppendRun".}
proc appendRun*(this: var Paragraph; text: CppString; fontSize: cdouble): Run {.
    importcpp: "AppendRun".}
proc appendRun*(this: var Paragraph; text: CppString; fontSize: cdouble; fontAscii: CppString;
               fontEastAsia: CppString = ""): Run {.importcpp: "AppendRun".}
proc appendPageBreak*(this: var Paragraph): Run {.importcpp: "AppendPageBreak".}

proc setAlignment*(this: var Paragraph; alignment: ParagraphAlignment) {.
    importcpp: "SetAlignment".}
proc setLineSpacingSingle*(this: var Paragraph) {.importcpp: "SetLineSpacingSingle".}
proc setLineSpacingLines*(this: var Paragraph; at: cdouble) {.
    importcpp: "SetLineSpacingLines".}
proc setLineSpacingAtLeast*(this: var Paragraph; at: cint) {.
    importcpp: "SetLineSpacingAtLeast".}
proc setLineSpacingExactly*(this: var Paragraph; at: cint) {.
    importcpp: "SetLineSpacingExactly".}
proc setLineSpacing*(this: var Paragraph; at: cint; lineRule: cstring) {.
    importcpp: "SetLineSpacing".}
proc setBeforeSpacingAuto*(this: var Paragraph) {.importcpp: "SetBeforeSpacingAuto".}
proc setAfterSpacingAuto*(this: var Paragraph) {.importcpp: "SetAfterSpacingAuto".}
proc setSpacingAuto*(this: var Paragraph; attrNameAuto: cstring) {.
    importcpp: "SetSpacingAuto".}
proc setBeforeSpacingLines*(this: var Paragraph; beforeSpacing: cdouble) {.
    importcpp: "SetBeforeSpacingLines".}
proc setAfterSpacingLines*(this: var Paragraph; afterSpacing: cdouble) {.
    importcpp: "SetAfterSpacingLines".}
proc setBeforeSpacing*(this: var Paragraph; beforeSpacing: cint) {.
    importcpp: "SetBeforeSpacing".}
proc setAfterSpacing*(this: var Paragraph; afterSpacing: cint) {.
    importcpp: "SetAfterSpacing".}
proc setSpacing*(this: var Paragraph; twip: cint; attrNameAuto: cstring;
                attrName: cstring) {.importcpp: "SetSpacing".}
proc setLeftIndentChars*(this: var Paragraph; leftIndent: cdouble) {.
    importcpp: "SetLeftIndentChars".}
proc setRightIndentChars*(this: var Paragraph; rightIndent: cdouble) {.
    importcpp: "SetRightIndentChars".}
proc setLeftIndent*(this: var Paragraph; leftIndent: cint) {.
    importcpp: "SetLeftIndent".}
proc setRightIndent*(this: var Paragraph; rightIndent: cint) {.
    importcpp: "SetRightIndent".}
proc setFirstLineChars*(this: var Paragraph; indent: cdouble) {.
    importcpp: "SetFirstLineChars".}
proc setHangingChars*(this: var Paragraph; indent: cdouble) {.
    importcpp: "SetHangingChars".}
proc setFirstLine*(this: var Paragraph; indent: cint) {.importcpp: "SetFirstLine".}
proc setHanging*(this: var Paragraph; indent: cint) {.importcpp: "SetHanging".}
proc setIndent*(this: var Paragraph; indent: cint; attrName: cstring) {.
    importcpp: "SetIndent".}
proc setTopBorder*(this: var Paragraph; style: BoxBorderStyle = Single;
                  width: cdouble = 0.5; color: cstring = "auto") {.
    importcpp: "SetTopBorder".}
proc setBottomBorder*(this: var Paragraph; style: BoxBorderStyle = Single;
                     width: cdouble = 0.5; color: cstring = "auto") {.
    importcpp: "SetBottomBorder".}
proc setLeftBorder*(this: var Paragraph; style: BoxBorderStyle = Single;
                   width: cdouble = 0.5; color: cstring = "auto") {.
    importcpp: "SetLeftBorder".}
proc setRightBorder*(this: var Paragraph; style: BoxBorderStyle = Single;
                    width: cdouble = 0.5; color: cstring = "auto") {.
    importcpp: "SetRightBorder".}
proc setBorders*(this: var Paragraph; style: BoxBorderStyle = Single; width: cdouble = 0.5;
                color: cstring = "auto") {.importcpp: "SetBorders".}
# proc setBorders_*(this: var Paragraph; elemName: cstring; style: BoxBorderStyle;
                 # width: cdouble; color: cstring) {.importcpp: "SetBorders_".}
proc setFontSize*(this: var Paragraph; fontSize: cdouble) {.importcpp: "SetFontSize".}
proc setFont*(this: var Paragraph; fontAscii: CppString; fontEastAsia: CppString = "") {.
    importcpp: "SetFont".}
proc setFontStyle*(this: var Paragraph; fontStyle: RunFontStyle) {.
    importcpp: "SetFontStyle".}
proc setCharacterSpacing*(this: var Paragraph; characterSpacing: cint) {.
    importcpp: "SetCharacterSpacing".}
proc getText*(this: var Paragraph): CppString {.importcpp: "GetText".}
proc getSection*(this: var Paragraph): Section {.importcpp: "GetSection".}
proc insertSectionBreak*(this: var Paragraph): Section {.
    importcpp: "InsertSectionBreak".}
proc removeSectionBreak*(this: var Paragraph): Section {.
    importcpp: "RemoveSectionBreak".}
proc hasSectionBreak*(this: var Paragraph): bool {.importcpp: "HasSectionBreak".}
##  class Paragraph

proc constructTextFrame*(): TextFrame {.constructor,
                                     importcpp: "docx::TextFrame(@)".}
proc constructTextFrame*(tf: TextFrame): TextFrame {.constructor,
    importcpp: "docx::TextFrame(@)".}
proc destroyTextFrame*(this: var TextFrame) {.importcpp: "#.~TextFrame()".}
proc setSize*(this: var TextFrame; w: cint; h: cint) {.importcpp: "SetSize".}

# proc setAnchor_*(this: var TextFrame; attrName: cstring; anchor: TextFrameAnchor) {.
    # importcpp: "SetAnchor_".}
# proc setPosition_*(this: var TextFrame; attrName: cstring; align: TextFramePosition) {.
    # importcpp: "SetPosition_".}
# proc setPosition_*(this: var TextFrame; attrName: cstring; twip: cint) {.
    # importcpp: "SetPosition_".}
proc setPositionX*(this: var TextFrame; align: TextFramePosition;
                  ralativeTo: TextFrameAnchor) {.importcpp: "SetPositionX".}
proc setPositionY*(this: var TextFrame; align: TextFramePosition;
                  ralativeTo: TextFrameAnchor) {.importcpp: "SetPositionY".}
proc setPositionX*(this: var TextFrame; x: cint; ralativeTo: TextFrameAnchor) {.
    importcpp: "SetPositionX".}
proc setPositionY*(this: var TextFrame; y: cint; ralativeTo: TextFrameAnchor) {.
    importcpp: "SetPositionY".}

proc setTextWrapping*(this: var TextFrame; wrapping: TextFrameWrapping) {.
    importcpp: "SetTextWrapping".}
##  class TextFrame

proc constructBookmark*(): Bookmark {.constructor, importcpp: "docx::Bookmark(@)".}
proc constructBookmark*(rhs: Bookmark): Bookmark {.constructor,
    importcpp: "docx::Bookmark(@)".}
proc destroyBookmark*(this: var Bookmark) {.importcpp: "#.~Bookmark()".}
proc `==`*(this: var Bookmark; rhs: Bookmark): bool {.importcpp: "(# == #)".}
proc getId*(this: Bookmark): cuint {.noSideEffect, importcpp: "GetId".}
proc getName*(this: Bookmark): CppString {.noSideEffect, importcpp: "GetName".}

proc constructDocument*(): Document {.constructor, importcpp: "docx::Document(@)".}
proc destroyDocument*(this: var Document) {.importcpp: "#.~Document()".}
proc save*(this: var Document; path: CppString): bool {.importcpp: "Save".}
proc open*(this: var Document; path: CppString): bool {.importcpp: "Open".}
proc firstParagraph*(this: var Document): Paragraph {.importcpp: "FirstParagraph".}
proc lastParagraph*(this: var Document): Paragraph {.importcpp: "LastParagraph".}
proc appendParagraph*(this: var Document): Paragraph {.importcpp: "AppendParagraph".}
proc appendParagraph*(this: var Document; text: CppString): Paragraph {.
    importcpp: "AppendParagraph".}
proc appendParagraph*(this: var Document; text: CppString; fontSize: cdouble): Paragraph {.
    importcpp: "AppendParagraph".}
proc appendParagraph*(this: var Document; text: CppString; fontSize: cdouble;
                     fontAscii: CppString; fontEastAsia: CppString = ""): Paragraph {.
    importcpp: "AppendParagraph".}
proc prependParagraph*(this: var Document): Paragraph {.
    importcpp: "PrependParagraph".}
proc prependParagraph*(this: var Document; text: CppString): Paragraph {.
    importcpp: "PrependParagraph".}
proc prependParagraph*(this: var Document; text: CppString; fontSize: cdouble): Paragraph {.
    importcpp: "PrependParagraph".}
proc prependParagraph*(this: var Document; text: CppString; fontSize: cdouble;
                      fontAscii: CppString; fontEastAsia: CppString = ""): Paragraph {.
    importcpp: "PrependParagraph".}
proc insertParagraphBefore*(this: var Document; p: Paragraph): Paragraph {.
    importcpp: "InsertParagraphBefore".}
proc insertParagraphAfter*(this: var Document; p: Paragraph): Paragraph {.
    importcpp: "InsertParagraphAfter".}
proc removeParagraph*(this: var Document; p: var Paragraph): bool {.
    importcpp: "RemoveParagraph".}
proc appendPageBreak*(this: var Document): Paragraph {.importcpp: "AppendPageBreak".}
proc firstSection*(this: var Document): Section {.importcpp: "FirstSection".}
proc lastSection*(this: var Document): Section {.importcpp: "LastSection".}
proc appendSectionBreak*(this: var Document): Paragraph {.
    importcpp: "AppendSectionBreak".}
proc appendTable*(this: var Document; rows: cint; cols: cint): Table {.
    importcpp: "AppendTable".}
proc removeTable*(this: var Document; tbl: var Table) {.importcpp: "RemoveTable".}
proc appendTextFrame*(this: var Document; w: cint; h: cint): TextFrame {.
    importcpp: "AppendTextFrame".}
proc setReadOnly*(this: var Document; enabled: bool = true) {.importcpp: "SetReadOnly".}
proc getVars*(this: var Document): CppMap[string, string] {.importcpp: "GetVars".}
proc setVars*(this: var Document; vars: CppMap[string, string]) {.importcpp: "SetVars".}
proc addVars*(this: var Document; vars: CppMap[string, string]) {.importcpp: "AddVars".}
proc findBookmarks*(this: var Document) {.importcpp: "FindBookmarks".}
proc getBookmarks*(this: var Document): CppVector[Bookmark] {.importcpp: "GetBookmarks".}
proc addBookmark*(this: var Document; name: CppString; start: Run; `end`: Run): Bookmark {.
  importcpp: "AddBookmark".}
proc removeBookmark*(this: var Document; b: var Bookmark) {.
    importcpp: "RemoveBookmark".}
##  class Document

##  namespace docx
